/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import common.Role;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import model.Author;
import model.AuthorDirectory;
import model.Book;
import model.BookCollection;
import model.BranchManager;
import model.CustomerDirectory;
import model.EmployeeDirectory;
import model.LibraryDirectory;
import model.UserDirectory;
import org.w3c.dom.UserDataHandler;
import ui.Admin.AdminWorkspace;
import ui.BranchManager.BranchManagerWorkspace;
import ui.BranchManager.ManagerLogin;
import ui.Customer.CustomerWorkspace;
import ui.Customer.WelcomePage;
import utils.NavigationUtils;

/**
 *
 * @author tisaac
 */
public class MainJFrame extends javax.swing.JFrame {
    
    NavigationUtils nv;
    AuthorDirectory authorList;
    UserDirectory userList;
    LibraryDirectory libList;
    EmployeeDirectory emList;
    BookCollection allBooks;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        nv = new NavigationUtils(WorkArea);
        fakeDataGenerator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        CtrlArea = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnBranchManager = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPanel.setDividerLocation(150);
        SplitPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnBranchManager.setText("Branch Manager");
        btnBranchManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBranchManagerActionPerformed(evt);
            }
        });

        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CtrlAreaLayout = new javax.swing.GroupLayout(CtrlArea);
        CtrlArea.setLayout(CtrlAreaLayout);
        CtrlAreaLayout.setHorizontalGroup(
            CtrlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CtrlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CtrlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CtrlAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CtrlAreaLayout.setVerticalGroup(
            CtrlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CtrlAreaLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnBranchManager)
                .addGap(18, 18, 18)
                .addComponent(btnCustomer)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(CtrlArea);

        WorkArea.setLayout(new java.awt.CardLayout());
        SplitPanel.setRightComponent(WorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        AdminWorkspace adminWork = new AdminWorkspace(nv);
        nv.showCard(adminWork, "AdminWorkspace");
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnBranchManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBranchManagerActionPerformed
        ManagerLogin mngLogin = new ManagerLogin(nv);
        nv.showCard(mngLogin, "ManagerLogin");
    }//GEN-LAST:event_btnBranchManagerActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        WelcomePage cWelcome = new WelcomePage(nv);
        nv.showCard(cWelcome, "WelcomePage");
    }//GEN-LAST:event_btnCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CtrlArea;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBranchManager;
    private javax.swing.JButton btnCustomer;
    // End of variables declaration//GEN-END:variables

    public void nextCard(JPanel jpanel, String name) { 
        WorkArea.add(name, jpanel);
        CardLayout ly = (CardLayout) WorkArea.getLayout();
        ly.next(WorkArea);
    }

    
    private void fakeDataGenerator() {
        try {
            this.userList = UserDirectory.getInstance();
            this.libList = LibraryDirectory.getInstance();
            this.emList = EmployeeDirectory.getInstance();
            this.allBooks = BookCollection.getInstance();
            this.authorList = AuthorDirectory.getInstance();

            // Branch Manager
            BranchManager bm1 = userList.createBranchManager("Alice Johnson", "alicepwd", Role.BRANCH_MANAGER);
            BranchManager bm2 = userList.createBranchManager("Bob Smith", "bobpwd", Role.BRANCH_MANAGER);

            // Library
            libList.addLibrary("Central Library", 101, bm1);
            libList.addLibrary("Westside Library", 202, bm2);

            // Admin
            userList.createAdmin("AdminUser", "adminpwd", Role.ADMIN);

            // Custom
            userList.createCustomer("Tom Hanks", "tom123", Role.CUSTOMER);
            userList.createCustomer("Emma Watson", "emma456", Role.CUSTOMER);
            userList.createCustomer("Chris Evans", "chris789", Role.CUSTOMER);
            
            // Authors
            Author jk = authorList.addAuthor("J.K. Rowling", "UK", null);
            Author grr = authorList.addAuthor("George R.R. Martin", "USA", null);
            Author hm = authorList.addAuthor("Haruki Murakami", "Japan", null);
            Author ja = authorList.addAuthor("Jane Austen", "UK", null);
            Author sk = authorList.addAuthor("Stephen King", "USA", null);

            // Books
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            Book b1 = allBooks.addNewBook("Harry Potter", sdf.parse("2024-01-01"), libList.getLibraryByName("Central Library"), jk, 200, "English", (short)123);
            Book b2 = allBooks.addNewBook("Game of Thrones", sdf.parse("2024-01-02"), libList.getLibraryByName("Central Library"), grr, 100, "Frensh", (short)234);
            Book b3 = allBooks.addNewBook("Norwegian Wood", sdf.parse("2024-01-03"), libList.getLibraryByName("Westside Library"), hm, 1230, "Mandaran", (short)10);
            Book b4 = allBooks.addNewBook("Pride and Prejudice", sdf.parse("2024-01-04"), libList.getLibraryByName("Westside Library"), jk, 2340, "Japanese", (short)132);
            Book b5 = allBooks.addNewBook("The Shining", sdf.parse("2024-01-05"), libList.getLibraryByName("Central Library"), jk, 999, "Cantonese", (short)333);
            
            jk.getBooks().add(b1);
            grr.getBooks().add(b2);
            hm.getBooks().add(b3);
            jk.getBooks().add(b4);
            jk.getBooks().add(b5);
            
        } catch (Exception e) {
            System.out.println("Error configuring system: " + e.getMessage());
        }
        
    }
}
