/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.vehicle;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Owner;
import model.OwnerDirectory;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import model.VehicleDirectory;

/**
 *
 * @author tisaac
 */
public class OwnerVehicleJPanel extends javax.swing.JPanel {
    
    JPanel mainWorkArea;
    ServiceCatalog serviceCatalog;
    VehicleDirectory vehicleDir;
    OwnerDirectory ownerDir;
    

    /**
     * Creates new form OwnerVehicleJPanel
     */
    public OwnerVehicleJPanel(JPanel mainWorkArea, ServiceCatalog serviceCatalog, VehicleDirectory vehicleDir, OwnerDirectory ownerDir) {
        initComponents();
        this.setSize(800, 800);
        this.mainWorkArea = mainWorkArea;
        this.serviceCatalog = serviceCatalog;
        this.vehicleDir = vehicleDir;
        this.ownerDir = ownerDir;
        
        popServices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblServiceDate = new javax.swing.JLabel();
        txtServiceDate = new javax.swing.JTextField();
        lblOwnerID = new javax.swing.JLabel();
        txtOwnerID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblOwnerTitle1 = new javax.swing.JLabel();
        vehicleJPanel = new javax.swing.JPanel();
        txtMake = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblRegistrationNum = new javax.swing.JLabel();
        lblOwnerTitle = new javax.swing.JLabel();
        txtRegistrationNum = new javax.swing.JTextField();
        cmbServiceOpted = new javax.swing.JComboBox<>();
        lblServiceOpted = new javax.swing.JLabel();
        lblVehicleID = new javax.swing.JLabel();
        txtVehicleID = new javax.swing.JTextField();
        lblMake = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();

        lblLastName.setText("Last Name");

        lblServiceDate.setText("Service Date");

        lblOwnerID.setText("Owner ID");

        lblFirstName.setText("First Name");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOwnerTitle1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblOwnerTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOwnerTitle1.setText("Owner Details");

        vehicleJPanel.setBackground(new java.awt.Color(102, 102, 102));

        lblModel.setText("Model");

        lblRegistrationNum.setText("Registration Number");

        lblOwnerTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblOwnerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOwnerTitle.setText("Vehicle Details");

        lblServiceOpted.setText("Service Opted");

        lblVehicleID.setText("Vehicle ID");

        lblMake.setText("Make");

        lblYear.setText("Year");

        javax.swing.GroupLayout vehicleJPanelLayout = new javax.swing.GroupLayout(vehicleJPanel);
        vehicleJPanel.setLayout(vehicleJPanelLayout);
        vehicleJPanelLayout.setHorizontalGroup(
            vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOwnerTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(vehicleJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYear)
                    .addComponent(lblVehicleID)
                    .addComponent(lblMake)
                    .addComponent(lblModel)
                    .addComponent(lblRegistrationNum)
                    .addComponent(lblServiceOpted))
                .addGap(58, 58, 58)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistrationNum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        vehicleJPanelLayout.setVerticalGroup(
            vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblOwnerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleID))
                .addGap(18, 18, 18)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMake))
                .addGap(18, 18, 18)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addGap(18, 18, 18)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegistrationNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistrationNum))
                .addGap(18, 18, 18)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear))
                .addGap(18, 18, 18)
                .addGroup(vehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiceOpted)
                    .addComponent(cmbServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        vehicleJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblMake, lblModel, lblRegistrationNum, lblServiceOpted, lblVehicleID});

        btnRegister.setText("Register Service");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOwnerTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName)
                                    .addComponent(lblServiceDate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOwnerID)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(vehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblOwnerTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerID)
                    .addComponent(txtOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDate)
                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(vehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRegister)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainWorkArea.remove(this);
        
        JFrame frame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(mainWorkArea);
        if (frame != null) {
            frame.setSize(800, 600);
            frame.revalidate();
            frame.repaint();
        }

        CardLayout ly = (CardLayout) mainWorkArea.getLayout();
        ly.previous(mainWorkArea);
        
        mainWorkArea.revalidate(); 
        mainWorkArea.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // Get Owner and Vehicle data
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String serviceDateStr = txtServiceDate.getText().trim();
        String ownerID = txtOwnerID.getText().trim();
        String model = txtModel.getText().trim();
        String make = txtMake.getText().trim();
        String registrationNum = txtRegistrationNum.getText().trim();
        String vehicleID = txtVehicleID.getText().trim();
        String yearStr = txtYear.getText().trim();
        String selectedService = cmbServiceOpted.getSelectedItem().toString();
        
        // Validate Required Fields
        if (firstName.isEmpty() || lastName.isEmpty() || serviceDateStr.isEmpty() || 
            ownerID.isEmpty() || model.isEmpty() || make.isEmpty() || registrationNum.isEmpty() || 
            vehicleID.isEmpty() || yearStr.isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedService.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create a service first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate serviceDate (Must be a valid long)
        long serviceDate;
        try {
            serviceDate = Long.parseLong(serviceDateStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Service Date must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate Year (Must be a valid year)
        int year;
        try {
            year = Integer.parseInt(yearStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Year must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        // Create an Owner
        Owner owner = ownerDir.addNewOwner();
        owner.setFirstName(firstName);
        owner.setLastName(lastName);
        owner.setId(ownerID);
        owner.setServiceDate(serviceDate);
        
        
        Vehicle v = vehicleDir.addNewVehicle();
        v.setId(vehicleID);
        v.setMake(make);
        v.setModel(model);
        v.setRegistrationNum(registrationNum);
        v.setYear(year);
        
        for (Service s : serviceCatalog.getServiceCatalog()) {
            if (selectedService == s.getType()) {
                v.setServiceOpted(s);
                break;
            }
        }
        
        owner.setVehicle(v);
        
        clearFields();
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbServiceOpted;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerID;
    private javax.swing.JLabel lblOwnerTitle;
    private javax.swing.JLabel lblOwnerTitle1;
    private javax.swing.JLabel lblRegistrationNum;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblVehicleID;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerID;
    private javax.swing.JTextField txtRegistrationNum;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtYear;
    private javax.swing.JPanel vehicleJPanel;
    // End of variables declaration//GEN-END:variables

    private void popServices() {
        cmbServiceOpted.removeAllItems();
        
        if (serviceCatalog.getServiceCatalog() == null) {
        System.out.println("Service catalog is null!");
        return;
    }
        
        for (Service s : serviceCatalog.getServiceCatalog()) {
            cmbServiceOpted.addItem(s.toString());
        }
    }
    
    private void clearFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtServiceDate.setText("");
        txtOwnerID.setText("");
        txtModel.setText("");
        txtMake.setText("");
        txtRegistrationNum.setText("");
        txtVehicleID.setText("");
        txtYear.setText("");
        cmbServiceOpted.setSelectedIndex(-1); // Reset JComboBox selection
    }
    
    
}
