/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.OwnerDirectory;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import model.VehicleDirectory;

/**
 *
 * @author tisaac
 */
public class MaimJFrame extends javax.swing.JFrame {
    
    VehicleDirectory vehicleDir;
    ServiceCatalog serviceCatalog;
    OwnerDirectory ownerDir;

    /**
     * Creates new form MaimJFrame
     */
    public MaimJFrame() {
        initComponents();
        
        vehicleDir = new VehicleDirectory();
        serviceCatalog = new ServiceCatalog();
        ownerDir = new OwnerDirectory();
        
        setSize(800, 600);
        
        populateVehicleDirectory();
        setStartUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainWorkArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaimJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaimJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaimJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaimJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaimJFrame().setVisible(true);
            }
        });
    }

    private void setStartUp() {
        StartPageJPanel startUp = new StartPageJPanel(mainWorkArea, vehicleDir, serviceCatalog, ownerDir);
        mainWorkArea.add("startPage", startUp);
        CardLayout ly = (CardLayout) mainWorkArea.getLayout();
        ly.next(mainWorkArea);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables

    private void populateVehicleDirectory() {
    // 創建一些預設的 Service
    Service oil = serviceCatalog.addNewServiceWithData("S001", "Oil Change", 50.0, "John Doe", (short) 30);
    Service carWash = serviceCatalog.addNewServiceWithData("S002", "Car Wash", 20.0, "Jane Smith", (short) 15);
    Service tire = serviceCatalog.addNewServiceWithData("S003", "Tire Rotation", 40.0, "Tom Brown", (short) 45);

    // 創建 Owner & Vehicle
    
    Vehicle v1 = vehicleDir.addNewVehicleWithData("V001", "Toyota", "Camry", 2020, "ABC123", oil);
    ownerDir.addNewOwnerWithData("O001", "Alice", "Johnson", 20250210, v1);

    
    Vehicle v2 = vehicleDir.addNewVehicleWithData("V002", "Honda", "Civic", 2022, "XYZ789", carWash);
    ownerDir.addNewOwnerWithData("O002", "Bob", "Smith", 20250310, v2);

    
    Vehicle v3 = vehicleDir.addNewVehicleWithData("V003", "Toyota", "Camry", 2019, "LMN456", tire);
    ownerDir.addNewOwnerWithData("O003", "Charlie", "Brown", 20250801, v3);

    
    Vehicle v4 = vehicleDir.addNewVehicleWithData("V004", "Ford", "F-150", 2021, "JKL321", oil);
    ownerDir.addNewOwnerWithData("O004", "David", "Williams", 20250901, v4);

    
    Vehicle v5 = vehicleDir.addNewVehicleWithData("V005", "Honda", "Civic", 2023, "GHI987", carWash);
    ownerDir.addNewOwnerWithData("O005", "Emma", "Davis", 20260311, v5);
}
}
