/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.lang.reflect.Method;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.TripProfile;

/**
 *
 * @author tisaac
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    TripProfile tripProfile;
    private JTextField[] textFields;
    private JComboBox[] comboBoxes;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(TripProfile t) {
        tripProfile = t;
        initComponents();
               
        // Initialize the arrays AFTER components exist
        textFields = new JTextField[]{
            txtName, txtDestination, txtStartDate, txtEndDate, txtBudget,
            txtTravelerCount, txtTransportMode, txtEmergencyC, txtNotes,
            txtTravelerEmail, txtTravelerPhone, txtBookingRef, txtExchangeRate,
            txtFavSpots, txtPackingList, txtInsurance
        };

        comboBoxes = new JComboBox[]{
            cbAccommodation, cbStatus, cbTripPurpose, cbVisa
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        lbStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lbEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lbBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        lbTravelerCount = new javax.swing.JLabel();
        txtTravelerCount = new javax.swing.JTextField();
        txtExchangeRate = new javax.swing.JTextField();
        lbFavSpots = new javax.swing.JLabel();
        lbTravelerEmail = new javax.swing.JLabel();
        txtFavSpots = new javax.swing.JTextField();
        txtTravelerEmail = new javax.swing.JTextField();
        lbTravelerPhone = new javax.swing.JLabel();
        txtTravelerPhone = new javax.swing.JTextField();
        lbBookingRef = new javax.swing.JLabel();
        txtBookingRef = new javax.swing.JTextField();
        lbStatus = new javax.swing.JLabel();
        lbExchangeRate = new javax.swing.JLabel();
        txtPackingList = new javax.swing.JTextField();
        lbInsurance = new javax.swing.JLabel();
        lbTransportMode = new javax.swing.JLabel();
        txtInsurance = new javax.swing.JTextField();
        txtTransportMode = new javax.swing.JTextField();
        lbAccommodation = new javax.swing.JLabel();
        lbEmergencyC = new javax.swing.JLabel();
        txtEmergencyC = new javax.swing.JTextField();
        lbNotes = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        lbPackingList = new javax.swing.JLabel();
        lbVisa = new javax.swing.JLabel();
        lbTripPurpose = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        cbAccommodation = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        cbVisa = new javax.swing.JComboBox<>();
        cbTripPurpose = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(520, 500));

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Create Travel Profile");

        lbName.setText("name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lbDestination.setText("destination:");

        lbStartDate.setText("startDate:");

        lbEndDate.setText("endDate:");

        lbBudget.setText("budget:");

        lbTravelerCount.setText("travelerCount:");

        lbFavSpots.setText("favoritiesSpots:");

        lbTravelerEmail.setText("travelerEmail:");

        lbTravelerPhone.setText("travelerPhone:");

        lbBookingRef.setText("bookingRef:");

        lbStatus.setText("status:");

        lbExchangeRate.setText("exchangeRate:");

        lbInsurance.setText("insurance:");

        lbTransportMode.setText("transportMode:");

        lbAccommodation.setText("accommodation:");

        lbEmergencyC.setText("emergencyContact:");

        lbNotes.setText("notes:");

        lbPackingList.setText("packingList:");

        lbVisa.setText("visaRequirement:");

        lbTripPurpose.setText("tripPurpose:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbAccommodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "Airbnb", "Camping" }));
        cbAccommodation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAccommodationItemStateChanged(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planned", "Ongoing", "Completed" }));

        cbVisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        cbTripPurpose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leisure", "Business" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStartDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEndDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBudget, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTravelerCount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTransportMode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAccommodation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmergencyC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtEmergencyC, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtTransportMode, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtTravelerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(txtDestination, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(cbAccommodation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTravelerEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTravelerPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBookingRef, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbExchangeRate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFavSpots, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbInsurance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTripPurpose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPackingList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbVisa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBookingRef)
                    .addComponent(txtTravelerPhone)
                    .addComponent(txtExchangeRate)
                    .addComponent(txtFavSpots)
                    .addComponent(txtPackingList)
                    .addComponent(txtInsurance)
                    .addComponent(cbVisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTripPurpose, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTravelerEmail))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDestination)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStartDate)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEndDate)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBudget)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerCount)
                            .addComponent(txtTravelerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerEmail)
                            .addComponent(txtTravelerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerPhone)
                            .addComponent(txtTravelerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBookingRef)
                            .addComponent(txtBookingRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStatus)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbExchangeRate)
                            .addComponent(txtExchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFavSpots)
                            .addComponent(txtFavSpots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTransportMode)
                        .addComponent(txtTransportMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPackingList)
                            .addComponent(txtPackingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbInsurance)
                            .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAccommodation))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmergencyC)
                            .addComponent(txtEmergencyC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNotes)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTripPurpose)
                            .addComponent(cbTripPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbVisa)
                            .addComponent(cbVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        createTravelProfile();
        
        JOptionPane.showMessageDialog(this, "Travel Profile Saved!", "Success", JOptionPane.PLAIN_MESSAGE);
        
        resetFields();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbAccommodationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAccommodationItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbAccommodationItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbAccommodation;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTripPurpose;
    private javax.swing.JComboBox<String> cbVisa;
    private javax.swing.JLabel lbAccommodation;
    private javax.swing.JLabel lbBookingRef;
    private javax.swing.JLabel lbBudget;
    private javax.swing.JLabel lbDestination;
    private javax.swing.JLabel lbEmergencyC;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbExchangeRate;
    private javax.swing.JLabel lbFavSpots;
    private javax.swing.JLabel lbInsurance;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNotes;
    private javax.swing.JLabel lbPackingList;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTransportMode;
    private javax.swing.JLabel lbTravelerCount;
    private javax.swing.JLabel lbTravelerEmail;
    private javax.swing.JLabel lbTravelerPhone;
    private javax.swing.JLabel lbTripPurpose;
    private javax.swing.JLabel lbVisa;
    private javax.swing.JTextField txtBookingRef;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmergencyC;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtExchangeRate;
    private javax.swing.JTextField txtFavSpots;
    private javax.swing.JTextField txtInsurance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtPackingList;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTransportMode;
    private javax.swing.JTextField txtTravelerCount;
    private javax.swing.JTextField txtTravelerEmail;
    private javax.swing.JTextField txtTravelerPhone;
    // End of variables declaration//GEN-END:variables

    
    
    private void createTravelProfile() {
//        String name = txtName.getText();
//        String destination = txtDestination.getText();
//        String startDate = txtStartDate.getText();
//        String endDate = txtEndDate.getText();
//        String budget = txtBudget.getText();
//        String travelerCount = txtTravelerCount.getText();
//        String transportMode = txtTransportMode.getText();
//        String accommodation = (String) cbAccommodation.getSelectedItem();
//        String emergencyContact = txtEmergencyC.getText();
//        String notes = txtNotes.getText();
//        String travelerEmail = txtTravelerEmail.getText();
//        String travelerPhone = txtTravelerPhone.getText();
//        String bookingRef = txtBookingRef.getText();
//        String status = (String) cbStatus.getSelectedItem();
//        String exchangeRate = txtExchangeRate.getText();
//        String favoritesSpots = txtFavSpots.getText();
//        String packingList = txtPackingList.getText();
//        String insurance = txtInsurance.getText();
//        String tripPurpose = (String) cbTripPurpose.getSelectedItem();
//        String visaRequirement = (String) cbVisa.getSelectedItem();
        
        
        String[] fieldNames = {
            "name", "destination", "startDate", "endDate", "budget",
            "travelerCount", "transportMode", "emergencyContact",
            "notes", "travelerEmail", "travelerPhone", "bookingRef",
            "exchangeRate", "favoritesSpots", "packingList", "insurance"
        };
        
        String[] comboBoxNames = {
            "accommodation", "status", "tripPurpose", "visaRequirement"
        };
        
        try {
            for (int i = 0; i < textFields.length; i++) {
                String fieldName = fieldNames[i];
                JTextField field = textFields[i];
                                
                // Use Reflection to find the corresponding getter method
                Method setter = tripProfile.getClass().getMethod("set" + capitalize(fieldName), String.class);
                
                setter.invoke(tripProfile, field.getText()); // calls the getter method dynamically.
            }
            
            for (int i = 0; i < comboBoxes.length; i++) {
                String fieldName = comboBoxNames[i];
                JComboBox comboBox = comboBoxes[i];
                
                Method setter = tripProfile.getClass().getMethod("set" + capitalize(fieldName), String.class);
                setter.invoke(tripProfile, comboBox.getSelectedItem().toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str; // Return empty or null as-is to avoid errors
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
    
    private void resetFields() {
        // Reset all JTextFields
        for (JTextField field : textFields) {
            field.setText("");
        }

        // Reset JComboBoxes
        for (JComboBox comboBox : comboBoxes) {
            comboBox.setSelectedIndex(0);
        }
    }

}
