/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.lang.reflect.Method;
import javax.swing.JTextField;
import model.TripProfile;

/**
 *
 * @author tisaac
 */
public class ViewJPanel extends javax.swing.JPanel {

    TripProfile tripProfile;
    
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(TripProfile t) {
        tripProfile = t;
        initComponents();
        
        displayFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        lbStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lbEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lbBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        lbTravelerCount = new javax.swing.JLabel();
        txtTravelerCount = new javax.swing.JTextField();
        txtExchangeRate = new javax.swing.JTextField();
        lbFavSpots = new javax.swing.JLabel();
        lbTravelerEmail = new javax.swing.JLabel();
        txtFavSpots = new javax.swing.JTextField();
        txtTravelerEmail = new javax.swing.JTextField();
        lbTravelerPhone = new javax.swing.JLabel();
        txtTravelerPhone = new javax.swing.JTextField();
        lbBookingRef = new javax.swing.JLabel();
        txtBookingRef = new javax.swing.JTextField();
        lbStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lbExchangeRate = new javax.swing.JLabel();
        txtPackingList = new javax.swing.JTextField();
        lbInsurance = new javax.swing.JLabel();
        lbTransportMode = new javax.swing.JLabel();
        txtInsurance = new javax.swing.JTextField();
        txtTransportMode = new javax.swing.JTextField();
        lbAccommodation = new javax.swing.JLabel();
        lbEmergencyC = new javax.swing.JLabel();
        txtEmergencyC = new javax.swing.JTextField();
        lbNotes = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        lbPackingList = new javax.swing.JLabel();
        txtTripPurpose = new javax.swing.JTextField();
        lbVisa = new javax.swing.JLabel();
        txtVisa = new javax.swing.JTextField();
        lbTripPurpose = new javax.swing.JLabel();
        txtAccommodation = new javax.swing.JTextField();

        jPanel1.setPreferredSize(new java.awt.Dimension(520, 500));

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Travel Profile");

        lbName.setText("name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lbDestination.setText("destination:");

        lbStartDate.setText("startDate:");

        lbEndDate.setText("endDate:");

        lbBudget.setText("budget:");

        lbTravelerCount.setText("travelerCount:");

        lbFavSpots.setText("favoritiesSpots:");

        lbTravelerEmail.setText("travelerEmail:");

        lbTravelerPhone.setText("travelerPhone:");

        lbBookingRef.setText("bookingRef:");

        lbStatus.setText("status:");

        lbExchangeRate.setText("exchangeRate:");

        lbInsurance.setText("insurance:");

        lbTransportMode.setText("transportMode:");

        txtTransportMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransportModeActionPerformed(evt);
            }
        });

        lbAccommodation.setText("accommodation:");

        lbEmergencyC.setText("emergencyContact:");

        lbNotes.setText("notes:");

        lbPackingList.setText("packingList:");

        lbVisa.setText("visaRequirement:");

        lbTripPurpose.setText("tripPurpose:");

        txtAccommodation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccommodationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStartDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEndDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBudget, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTravelerCount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTransportMode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAccommodation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmergencyC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmergencyC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTransportMode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTravelerCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBudget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTravelerEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTravelerPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBookingRef, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbExchangeRate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFavSpots, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbInsurance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTripPurpose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPackingList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbVisa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFavSpots)
                    .addComponent(txtInsurance)
                    .addComponent(txtPackingList)
                    .addComponent(txtVisa)
                    .addComponent(txtTripPurpose)
                    .addComponent(txtTravelerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txtTravelerPhone)
                    .addComponent(txtBookingRef)
                    .addComponent(txtStatus)
                    .addComponent(txtExchangeRate))
                .addGap(36, 36, 36))
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDestination)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStartDate)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEndDate)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBudget)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerCount)
                            .addComponent(txtTravelerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerEmail)
                            .addComponent(txtTravelerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTravelerPhone)
                            .addComponent(txtTravelerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBookingRef)
                            .addComponent(txtBookingRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStatus)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbExchangeRate)
                            .addComponent(txtExchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFavSpots)
                            .addComponent(txtFavSpots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTransportMode)
                        .addComponent(txtTransportMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPackingList)
                            .addComponent(txtPackingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbInsurance)
                            .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAccommodation)
                            .addComponent(txtAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmergencyC)
                            .addComponent(txtEmergencyC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNotes)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTripPurpose)
                            .addComponent(txtTripPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVisa)
                            .addComponent(txtVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAccommodationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccommodationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccommodationActionPerformed

    private void txtTransportModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransportModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransportModeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAccommodation;
    private javax.swing.JLabel lbBookingRef;
    private javax.swing.JLabel lbBudget;
    private javax.swing.JLabel lbDestination;
    private javax.swing.JLabel lbEmergencyC;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbExchangeRate;
    private javax.swing.JLabel lbFavSpots;
    private javax.swing.JLabel lbInsurance;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNotes;
    private javax.swing.JLabel lbPackingList;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTransportMode;
    private javax.swing.JLabel lbTravelerCount;
    private javax.swing.JLabel lbTravelerEmail;
    private javax.swing.JLabel lbTravelerPhone;
    private javax.swing.JLabel lbTripPurpose;
    private javax.swing.JLabel lbVisa;
    private javax.swing.JTextField txtAccommodation;
    private javax.swing.JTextField txtBookingRef;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmergencyC;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtExchangeRate;
    private javax.swing.JTextField txtFavSpots;
    private javax.swing.JTextField txtInsurance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtPackingList;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTransportMode;
    private javax.swing.JTextField txtTravelerCount;
    private javax.swing.JTextField txtTravelerEmail;
    private javax.swing.JTextField txtTravelerPhone;
    private javax.swing.JTextField txtTripPurpose;
    private javax.swing.JTextField txtVisa;
    // End of variables declaration//GEN-END:variables


    private void displayFields() {
        System.out.println("display button triggered!");
        
        // Ensure tripProfile exists
        if (tripProfile == null) {
            System.out.println("tripProfile is null! Initializing a new one.");
            tripProfile = new TripProfile();
        }
    
        JTextField[] textFields = {
            txtName, txtDestination, txtStartDate, txtEndDate, txtBudget,
            txtTravelerCount, txtTransportMode, txtAccommodation, txtEmergencyC, txtNotes,
            txtTravelerEmail, txtTravelerPhone, txtBookingRef, txtStatus, txtExchangeRate,
            txtFavSpots, txtPackingList, txtInsurance, txtTripPurpose, txtVisa
        };
        
        String[] fieldNames = {
            "name", "destination", "startDate", "endDate", "budget",
            "travelerCount", "transportMode", "accommodation", "emergencyContact",
            "notes", "travelerEmail", "travelerPhone", "bookingRef", "status",
            "exchangeRate", "favoritesSpots", "packingList", "insurance",
            "tripPurpose", "visaRequirement"
        };
        
        try {
            for (int i = 0; i < textFields.length; i++) {
                JTextField field = textFields[i];
                String fieldName = fieldNames[i];
                
                // Use Reflection to find the corresponding getter method
                Method getter = tripProfile.getClass().getMethod("get" + capitalize(fieldName));
                Object value = getter.invoke(tripProfile); // calls the getter method dynamically.
                
                
                if (value != null) {
                    field.setText(value.toString());
                } else {
                    // Debugging: Check what values are retrieved
                    System.out.println("Field: " + fieldName + " | Value: " + value);
                    field.setText("");
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str; // Return empty or null as-is to avoid errors
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}
